openapi: 3.0.0
info:
  title: HelloWorld API
  version: 0.1.9
servers:
  - url: 'http://localhost:8080/'
paths:
  /helloworld:
    post:
      summary: Returns a hello.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
